### PR TITLE
Remove nginx_ssl_override_filename from defaults avoiding wrong certificate names

### LINKED ISSUE #10: Self signed ssl filename wrong
Hi all,

having nginx_ssl_override_filename default to '' will always result in the generated and configured ssl certificates to be name and added to configuration like `/etc/nginx/ssl/.pem`

Removing it from defaults solves the issue, but I am not sure this is the correct way to do so

### PR DESCRIPTION
**Pull request by speedmann**
This fixes #10

### CODE REVIEW

**Comment by speedmann** [comment]
I am doing this the first time, so I hope I did everything correct

**Comment by nickjj** [comment]
Hi, thanks.

What you did technically works, but you should also update the README.md file too.

Something like this should work:

```
# If defined, override the default value for SSL certificate names. If you
# leave this undefined, then it will become the file name of the first domain listed
# in the domains list when defining a virtual host (look in the next section).
#
# Setting this comes in handy if you use Let's Encrypt and want to register a
# single certificate that has multiple domains attached to it.
# nginx_ssl_override_filename: 'customcertname'
```

**Comment by speedmann** [comment]
hi there,
does anything need more fixes to be able to be merged?

**Comment by cristoper** [comment]
It would be nice if this were merged. As a workaround until then, I'm setting the variable explicitly in my playbook like:

`nginx_ssl_override_filename: "{{ letsencrypt_domains[0] }}"`

**Pull request merged**
